spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/blog
    username: postgres
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true  

# JWT properties
app:
  jwt-secret: 85777f270ad7cf2a790981bbae3c4e484a1dc55e24a77390d692fbf1cffa12fa # Replace with a strong, secure key #https://emn178.github.io/online-tools/sha256.html
  jwt-expiration-milliseconds: 3600000  # Token validity in milliseconds (1 hour)
  issuer: my-app       # Optional: Identify the application issuing the token
